"""The Runtime driver port: how odin runs + observes workloads on a host.

Two implementations, both live: `ColimaRuntime` (`colima.py`) runs containers
directly on Colima and is the default, and `LimaRuntime` (`lima.py`) runs them
inside a Lima VM for VM isolation. This used to call the Lima driver "a later
milestone"; it shipped, and `compute/instances.py` builds EC2 nodes as real
Lima VMs on top of it.

The data types live in `colima.py` (the concrete module) to keep the import
graph one-way (driver → colima).
"""
from __future__ import annotations

from typing import Protocol

from odin.runtime.colima import ContainerFacts, ContainerSpec, HostFacts, RunHandle

__all__ = ["RuntimeDriver", "ContainerSpec", "RunHandle", "ContainerFacts", "HostFacts"]


class RuntimeDriver(Protocol):
    async def ensure_host(self) -> HostFacts: ...
    async def run_container(self, spec: ContainerSpec) -> RunHandle: ...
    async def stop(self, name: str) -> None: ...
    async def facts(self, name: str, container_port: int = 0) -> ContainerFacts: ...
    async def stats(self, name: str) -> dict[str, float]: ...
    async def status(self, name: str) -> str: ...
    async def exit_code(self, name: str) -> int: ...
    async def container_id(self, name: str) -> str: ...
    async def network_mode(self, name: str) -> str: ...
    async def exec_sh(self, name: str, script: str) -> str: ...
    async def host_port(self, name: str, container_port: int) -> int: ...
    async def logs(self, name: str, tail: int = 20) -> str: ...
    async def signal(self, name: str, sig: str) -> None: ...
    async def copy_in(self, name: str, host_path: str, container_path: str) -> None: ...
    async def list_odin(self) -> list[str]: ...
    async def create_volume(self, name: str, env: str) -> None: ...
    async def remove_volume(self, name: str) -> None: ...
    async def volume_names(self, env: str | None = None) -> list[str]: ...
    async def image_exists(self, tag: str) -> bool: ...
    async def build(self, tag: str, dockerfile: str) -> None: ...
