// AUTO-GENERATED from MiniStack's SERVICE_REGISTRY by `python -m odin.aws.catalog_gen`. Do not edit by hand.
import type { ServiceDef } from './catalog';

// 47 AWS services for canvas parity with the embedded emulator.
export const GENERATED_CATALOG: ServiceDef[] = [
  {
    type: 'aws_acm', abbr: 'ACM', label: 'ACM', sublabel: 'AWS acm',
    category: 'AWS', color: 'cyan', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'acm' },
  },
  {
    type: 'aws_airflow', abbr: 'AIRF', label: 'Airflow', sublabel: 'AWS airflow',
    category: 'AWS', color: 'pink', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'airflow' },
  },
  {
    type: 'aws_appconfig', abbr: 'APPC', label: 'AppConfig', sublabel: 'AWS appconfig',
    category: 'AWS', color: 'rose', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'appconfig' },
  },
  {
    type: 'aws_appsync', abbr: 'APPS', label: 'AppSync', sublabel: 'AWS appsync',
    category: 'AWS', color: 'indigo', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'appsync' },
  },
  {
    type: 'aws_appsync_events', abbr: 'APPS', label: 'Appsync Events', sublabel: 'AWS appsync-events',
    category: 'AWS', color: 'lime', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'appsync-events' },
  },
  {
    type: 'aws_athena', abbr: 'ATHE', label: 'Athena', sublabel: 'AWS athena',
    category: 'AWS', color: 'amber', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'athena' },
  },
  {
    type: 'aws_autoscaling', abbr: 'AUTO', label: 'Autoscaling', sublabel: 'AWS autoscaling',
    category: 'AWS', color: 'teal', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'autoscaling' },
  },
  {
    type: 'aws_backup', abbr: 'BACK', label: 'Backup', sublabel: 'AWS backup',
    category: 'AWS', color: 'sky', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'backup' },
  },
  {
    type: 'aws_batch', abbr: 'BATC', label: 'Batch', sublabel: 'AWS batch',
    category: 'AWS', color: 'fuchsia', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'batch' },
  },
  {
    type: 'aws_cloudformation', abbr: 'CLOU', label: 'CloudFormation', sublabel: 'AWS cloudformation',
    category: 'AWS', color: 'cyan', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'cloudformation' },
  },
  {
    type: 'aws_cloudfront', abbr: 'CLOU', label: 'CloudFront', sublabel: 'AWS cloudfront',
    category: 'AWS', color: 'pink', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'cloudfront' },
  },
  {
    type: 'aws_cloudfront_keyvaluestore', abbr: 'CLOU', label: 'Cloudfront Keyvaluestore', sublabel: 'AWS cloudfront-keyvaluestore',
    category: 'AWS', color: 'rose', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'cloudfront-keyvaluestore' },
  },
  {
    type: 'aws_cloudtrail', abbr: 'CLOU', label: 'CloudTrail', sublabel: 'AWS cloudtrail',
    category: 'AWS', color: 'indigo', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'cloudtrail' },
  },
  {
    type: 'aws_codebuild', abbr: 'CODE', label: 'Codebuild', sublabel: 'AWS codebuild',
    category: 'AWS', color: 'lime', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'codebuild' },
  },
  {
    type: 'aws_cognito_identity', abbr: 'COGN', label: 'Cognito Identity', sublabel: 'AWS cognito-identity',
    category: 'AWS', color: 'amber', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'cognito-identity' },
  },
  {
    type: 'aws_cognito_idp', abbr: 'COGN', label: 'Cognito', sublabel: 'AWS cognito-idp',
    category: 'AWS', color: 'teal', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'cognito-idp' },
  },
  {
    type: 'aws_cur', abbr: 'CUR', label: 'Cur', sublabel: 'AWS cur',
    category: 'AWS', color: 'sky', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'cur' },
  },
  {
    type: 'aws_dynamodbstreams', abbr: 'DYNA', label: 'Dynamodbstreams', sublabel: 'AWS dynamodbstreams',
    category: 'AWS', color: 'fuchsia', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'dynamodbstreams' },
  },
  {
    type: 'aws_ecr', abbr: 'ECR', label: 'ECR', sublabel: 'AWS ecr',
    category: 'AWS', color: 'cyan', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'ecr' },
  },
  {
    type: 'aws_ecs_metadata', abbr: 'ECSM', label: 'Ecs Metadata', sublabel: 'AWS ecs-metadata',
    category: 'AWS', color: 'pink', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'ecs-metadata' },
  },
  {
    type: 'aws_eks', abbr: 'EKS', label: 'EKS', sublabel: 'AWS eks',
    category: 'AWS', color: 'rose', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'eks' },
  },
  {
    type: 'aws_elasticache', abbr: 'ELAS', label: 'ElastiCache', sublabel: 'AWS elasticache',
    category: 'AWS', color: 'indigo', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'elasticache' },
  },
  {
    type: 'aws_elasticfilesystem', abbr: 'ELAS', label: 'Elasticfilesystem', sublabel: 'AWS elasticfilesystem',
    category: 'AWS', color: 'lime', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'elasticfilesystem' },
  },
  {
    type: 'aws_elasticloadbalancing', abbr: 'ELAS', label: 'Elasticloadbalancing', sublabel: 'AWS elasticloadbalancing',
    category: 'AWS', color: 'amber', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'elasticloadbalancing' },
  },
  {
    type: 'aws_elasticmapreduce', abbr: 'ELAS', label: 'Elasticmapreduce', sublabel: 'AWS elasticmapreduce',
    category: 'AWS', color: 'teal', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'elasticmapreduce' },
  },
  {
    type: 'aws_firehose', abbr: 'FIRE', label: 'Firehose', sublabel: 'AWS firehose',
    category: 'AWS', color: 'sky', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'firehose' },
  },
  {
    type: 'aws_glue', abbr: 'GLUE', label: 'Glue', sublabel: 'AWS glue',
    category: 'AWS', color: 'fuchsia', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'glue' },
  },
  {
    type: 'aws_inspector2', abbr: 'INSP', label: 'Inspector2', sublabel: 'AWS inspector2',
    category: 'AWS', color: 'cyan', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'inspector2' },
  },
  {
    type: 'aws_iot', abbr: 'IOT', label: 'IoT Core', sublabel: 'AWS iot',
    category: 'AWS', color: 'pink', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'iot' },
  },
  {
    type: 'aws_iot_data', abbr: 'IOTD', label: 'Iot Data', sublabel: 'AWS iot-data',
    category: 'AWS', color: 'rose', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'iot-data' },
  },
  {
    type: 'aws_mediaconnect', abbr: 'MEDI', label: 'Mediaconnect', sublabel: 'AWS mediaconnect',
    category: 'AWS', color: 'indigo', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'mediaconnect' },
  },
  {
    type: 'aws_monitoring', abbr: 'MONI', label: 'Monitoring', sublabel: 'AWS monitoring',
    category: 'AWS', color: 'lime', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'monitoring' },
  },
  {
    type: 'aws_mq', abbr: 'MQ', label: 'Mq', sublabel: 'AWS mq',
    category: 'AWS', color: 'amber', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'mq' },
  },
  {
    type: 'aws_opensearch', abbr: 'OPEN', label: 'OpenSearch', sublabel: 'AWS opensearch',
    category: 'AWS', color: 'teal', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'opensearch' },
  },
  {
    type: 'aws_organizations', abbr: 'ORGA', label: 'Organizations', sublabel: 'AWS organizations',
    category: 'AWS', color: 'sky', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'organizations' },
  },
  {
    type: 'aws_rds_data', abbr: 'RDSD', label: 'Rds Data', sublabel: 'AWS rds-data',
    category: 'AWS', color: 'fuchsia', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'rds-data' },
  },
  {
    type: 'aws_s3files', abbr: 'S3FI', label: 'S3Files', sublabel: 'AWS s3files',
    category: 'AWS', color: 'cyan', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 's3files' },
  },
  {
    type: 'aws_s3tables', abbr: 'S3TA', label: 'S3Tables', sublabel: 'AWS s3tables',
    category: 'AWS', color: 'pink', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 's3tables' },
  },
  {
    type: 'aws_scheduler', abbr: 'SCHE', label: 'Scheduler', sublabel: 'AWS scheduler',
    category: 'AWS', color: 'rose', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'scheduler' },
  },
  {
    type: 'aws_servicediscovery', abbr: 'SERV', label: 'Servicediscovery', sublabel: 'AWS servicediscovery',
    category: 'AWS', color: 'indigo', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'servicediscovery' },
  },
  {
    type: 'aws_ses', abbr: 'SES', label: 'SES', sublabel: 'AWS ses',
    category: 'AWS', color: 'lime', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'ses' },
  },
  {
    type: 'aws_states', abbr: 'STAT', label: 'States', sublabel: 'AWS states',
    category: 'AWS', color: 'amber', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'states' },
  },
  {
    type: 'aws_tagging', abbr: 'TAGG', label: 'Tagging', sublabel: 'AWS tagging',
    category: 'AWS', color: 'teal', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'tagging' },
  },
  {
    type: 'aws_transfer', abbr: 'TRAN', label: 'Transfer', sublabel: 'AWS transfer',
    category: 'AWS', color: 'sky', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'transfer' },
  },
  {
    type: 'aws_waf', abbr: 'WAF', label: 'Waf', sublabel: 'AWS waf',
    category: 'AWS', color: 'fuchsia', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'waf' },
  },
  {
    type: 'aws_waf_regional', abbr: 'WAFR', label: 'Waf Regional', sublabel: 'AWS waf-regional',
    category: 'AWS', color: 'cyan', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'waf-regional' },
  },
  {
    type: 'aws_wafv2', abbr: 'WAFV', label: 'WAF v2', sublabel: 'AWS wafv2',
    category: 'AWS', color: 'pink', width: 200,
    fields: [{ key: 'label', label: 'Name', editable: true }],
    defaultData: { label: 'wafv2' },
  },
];
