"""A security group rule's port may be a RANGE — `tcp:8000-8100:0.0.0.0/0`.

The limit this closes read:

> **A security group's rules are a single port each.** `tcp:443:0.0.0.0/0`, not
> a range — so an imported ingress block with a port RANGE is reported and left
> out, and the regenerated group allows *less* than the source.

Read that last clause as the correctness bug it is rather than the missing
feature it looks like. Importing someone's Terraform and regenerating it handed
back a NARROWER firewall than they gave you. It was reported rather than silent,
which is the only reason it was a limit and not a scandal — but a round trip
that tightens a firewall has changed a security posture nobody asked it to
change.

The enforcement was never the missing piece: `fabric/nebula.py::
sg_rules_to_firewall` has always emitted `f"{from_port}-{to_port}"` when the
bounds differ, and nebula accepts that spelling. What was missing was the CANVAS
GRAMMAR and the two sides that read and write it.

TWO REQUIREMENTS WITH TEETH, and neither is "a range works":

1. **Nothing existing may move.** AWS's model is `from_port`/`to_port`, so a
   single port is the degenerate range and every canvas ever drawn must emit
   byte-identical HCL. A diff in every group's Terraform would show up as a
   change on the next apply.
2. **Both BOUNDS must survive the round trip.** A test that only checks the rule
   came back would pass while `8000-8100` returned as `8000-8000` — the original
   defect, wearing the new grammar.
"""
from __future__ import annotations

import shutil
import subprocess

import pytest

from odin.agent import hcl
from odin.agent.hcl import generate_tf, parse_sg_rule
from odin.agent.import_tf import parse_hcl_text
from odin.agent.translate import validate_refinement
from odin.fabric.nebula import sg_rules_to_firewall
from odin.spec.translate import canvas_to_stack

# Transcribed from the v0.8.16 emitter, NOT generated by the code under test --
# a ratchet built out of the thing it ratchets is no ratchet at all. This is the
# exact block a single-port ingress rule has always produced, alignment included
# (`tofu fmt` pads to the widest key, `cidr_blocks` at 11).
_PRE_RANGE_SINGLE_PORT_INGRESS = (
    "  ingress {\n"
    "    from_port   = 443\n"
    "    to_port     = 443\n"
    '    protocol    = "tcp"\n'
    '    cidr_blocks = ["0.0.0.0/0"]\n'
    "  }"
)


def _canvas(**sg_data: str) -> dict:
    """One VPC, one group to point identity rules AT, and the group under test."""
    return {
        "nodes": [
            {"id": "v", "type": "vpc", "position": {"x": 0, "y": 0}, "data": {"label": "net"}},
            {"id": "w", "type": "sg", "position": {"x": 0, "y": 0},
             "data": {"label": "web-sg", "vpc": "net", "ingressRules": "tcp:443:0.0.0.0/0"}},
            {"id": "s", "type": "sg", "position": {"x": 0, "y": 0},
             "data": {"label": "db-sg", "vpc": "net", **sg_data}},
        ],
        "edges": [],
    }


def _project(**sg_data: str):
    return generate_tf(canvas_to_stack(_canvas(**sg_data)))


def _main_tf(**sg_data: str) -> str:
    return _project(**sg_data).files["main.tf"]


def _db_sg_block(**sg_data: str) -> str:
    main_tf = _main_tf(**sg_data)
    rest = main_tf[main_tf.index('resource "aws_security_group" "db_sg"'):]
    return rest[:rest.index("\n}\n")]


# ---------------------------------------------------------------------------
# Requirement 1: existing canvases do not move
# ---------------------------------------------------------------------------


def test_a_single_port_emits_exactly_the_bytes_it_always_did():
    """The no-change requirement, and the reason this file leads with a
    transcribed literal. Every canvas drawn before ranges existed carries single
    ports; a shifted byte here is a diff in every security group on the next
    `tofu plan`."""
    assert _PRE_RANGE_SINGLE_PORT_INGRESS in _db_sg_block(ingressRules="tcp:443:0.0.0.0/0")


def test_a_single_port_parses_as_the_degenerate_range():
    """Why requirement 1 holds by construction rather than by care: `443` IS
    `(443, 443)`, so it reaches the identical emitter path a range does."""
    assert parse_sg_rule("tcp:443:0.0.0.0/0") == ("tcp", "443", "443", "0.0.0.0/0")


def test_the_wide_open_egress_default_is_untouched():
    """`-1:0:0.0.0.0/0` is what an EMPTY `egressRules` field emits, which is
    every pre-v0.8.14 canvas. It goes through the same parser now."""
    assert parse_sg_rule(hcl._DEFAULT_EGRESS_LINE) == ("-1", "0", "0", "0.0.0.0/0")
    assert "    from_port   = 0\n    to_port     = 0\n" in _db_sg_block()


# ---------------------------------------------------------------------------
# Requirement 2: the range reaches the file, with BOTH bounds
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("field,block", [("ingressRules", "ingress"), ("egressRules", "egress")])
def test_a_range_emits_both_bounds_in_both_directions(field: str, block: str):
    """Egress landed in v0.8.14 on the same grammar and one shared builder, so
    it must accept ranges in the same commit -- an outbound field that silently
    rejects `8000-8100` while the inbound one takes it is the worse half of a
    half-shipped feature."""
    text = _db_sg_block(**{field: "tcp:8000-8100:0.0.0.0/0"})
    assert f"  {block} {{" in text
    assert "    from_port   = 8000\n    to_port     = 8100\n" in text


def test_a_range_next_to_an_identity_peer_whose_label_contains_a_hyphen():
    """The interaction that had to be CHECKED rather than assumed. The range
    separator is `-` and `web-sg` is a perfectly ordinary canvas label -- but the
    peer is `parts[2]` of a `split(":", 2)` and the port is `parts[1]`, so the
    two never meet. If they did, this rule would resolve to no group at all."""
    text = _db_sg_block(ingressRules="tcp:8000-8100:web-sg")
    assert "    from_port       = 8000\n    to_port         = 8100\n" in text
    assert "    security_groups = [aws_security_group.web_sg.id]" in text


def test_an_ipv6_peer_is_still_declined_for_being_IPv6_not_for_arity():
    """The other interaction, and the parser trap this repo already paid for
    once: an IPv6 CIDR contains colons, a bare `split(":")` made
    `tcp:443:2001:db8::/32` five fields, and the WHOLE security group was
    discarded on an arity error. Adding a `-` to the port field must not
    resurrect that -- the reason has to stay the real one."""
    (reason,) = _project(ingressRules="tcp:8000-8100:2001:db8::/32").unsupported
    assert "is an IPv6 CIDR" in reason
    assert "expected one" not in reason and "malformed port range" not in reason


# ---------------------------------------------------------------------------
# The round trip, which is what the limit was actually about
# ---------------------------------------------------------------------------

_RANGED_TF = '''
resource "aws_vpc" "net" {
  cidr_block = "10.0.0.0/16"
  tags = { "odin:node" = "prod-vpc" }
}

resource "aws_security_group" "ranged" {
  name   = "ranged-sg"
  vpc_id = aws_vpc.net.id

  ingress {
    from_port   = 8000
    to_port     = 8100
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/16"]
  }

  egress {
    from_port   = 9000
    to_port     = 9500
    protocol    = "udp"
    cidr_blocks = ["10.0.0.0/16"]
  }
}
'''


def test_an_imported_range_keeps_both_bounds_on_the_canvas():
    """The import half. `8000-8100`, not `8000` and not `8000-8000`."""
    result = parse_hcl_text(_RANGED_TF)
    data = next(n["data"] for n in result.nodes if n["data"]["label"] == "ranged-sg")
    assert data["ingressRules"] == "tcp:8000-8100:10.0.0.0/16"
    assert data["egressRules"] == "udp:9000-9500:10.0.0.0/16"
    assert [w for w in result.warnings if "rule(s) could not be imported" in w] == []


def test_the_regenerated_group_is_neither_narrower_nor_wider_than_the_source():
    """THE WHOLE POINT. Import someone's Terraform, regenerate it, and the ports
    they gave you come back -- both ends of both rules, asserted separately,
    because a single `8000-8100 in text` assertion passes for a range that came
    back as `8000-8000` only if you are lucky about the substring."""
    imported = parse_hcl_text(_RANGED_TF)
    regenerated = generate_tf(
        canvas_to_stack({"nodes": imported.nodes, "edges": []}),
    ).files["main.tf"]

    assert "    from_port   = 8000\n    to_port     = 8100\n" in regenerated
    assert "    from_port   = 9000\n    to_port     = 9500\n" in regenerated
    # ...and named individually, so a failure says WHICH bound moved.
    assert "to_port     = 8000" not in regenerated, "the ingress range narrowed to its low bound"
    assert "from_port   = 8100" not in regenerated, "the ingress range narrowed to its high bound"
    assert "to_port     = 9000" not in regenerated, "the egress range narrowed to its low bound"


def test_a_second_round_trip_is_byte_identical():
    """Stability, not just fidelity: HCL -> canvas -> HCL -> canvas -> HCL must
    stop moving. A grammar that re-widens or re-narrows by one port per cycle
    would pass the test above and still drift a firewall over a few edits."""
    first = generate_tf(
        canvas_to_stack({"nodes": parse_hcl_text(_RANGED_TF).nodes, "edges": []}),
    ).files["main.tf"]
    second = generate_tf(
        canvas_to_stack({"nodes": parse_hcl_text(first).nodes, "edges": []}),
    ).files["main.tf"]
    assert second == first


# ---------------------------------------------------------------------------
# A malformed range is DECLINED, by name — never half-parsed
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("port", [
    "8000-",      # a separator with nothing after it. `high or low` would have
                  # made this `8000-8000` -- half a range, silently narrowed.
    "-8100",      # ...and the mirror image, which is also how `-1` is spelled.
    "8000-8100-8200",
    "8100-8000",  # REVERSED. AWS rejects to_port < from_port outright, and
                  # nebula would emit a span no packet can be inside.
    "8000 - 8100",
    "http-https",
])
def test_a_malformed_range_declines_the_group_and_names_the_line(port: str):
    line = f"tcp:{port}:0.0.0.0/0"
    (reason,) = _project(ingressRules=line).unsupported
    assert f"'{line}'" in reason, "the reason must name the offending rule, not just the field"
    assert "malformed port range" in reason
    assert f"'{port}'" in reason


def test_a_malformed_range_is_never_half_parsed():
    """The failure mode the message exists to prevent, stated as behaviour: a
    declined line produces NO rule at all. `8000-` must not reach the file as
    `from_port = 8000`."""
    project = _project(ingressRules="tcp:8000-:0.0.0.0/0")
    assert 'resource "aws_security_group" "db_sg"' not in project.files["main.tf"]
    assert "8000" not in project.files["main.tf"]


@pytest.mark.parametrize("port", ["8000-", "-8100", "8100-8000", "notaport"])
def test_a_malformed_port_never_parses(port: str):
    """The parser directly, so the guard is pinned below the message."""
    assert parse_sg_rule(f"tcp:{port}:0.0.0.0/0") is None


def test_a_bare_minus_one_port_is_still_declined():
    """`icmp:-1:...` was never drawable and still is not -- ROADMAP says so, and
    a range grammar is exactly the change that could have made that line stale by
    accident (`-1` splits into an empty low bound)."""
    assert parse_sg_rule("icmp:-1:0.0.0.0/0") is None


def test_the_generic_format_message_is_untouched_for_a_line_with_no_range():
    """A grammar extension is no excuse for rewording a message that was already
    correct. A line that never attempted a range gets the sentence it always
    got; the range-specific one is reserved for a port field containing `-`."""
    (reason,) = _project(ingressRules="443 from anywhere").unsupported
    assert reason == (
        'db-sg (sg): ingressRules: expected one "protocol:port:source" rule per line, '
        "e.g. tcp:443:0.0.0.0/0"
    )


# ---------------------------------------------------------------------------
# Downstream: what a range compiles to, and what tofu makes of the file
# ---------------------------------------------------------------------------


def test_nebula_compiles_a_span_to_the_range_spelling_it_accepts():
    """The enforcement end was already built -- this pins the shape the emitted
    `from_port`/`to_port` pair arrives in, so a future single-port assumption
    downstream fails here rather than in a mesh. Asserted in BOTH directions,
    since v0.8.17 compiles egress into `outbound` too and a range that gates
    inbound while silently widening outbound would be the worse half.

    NOT an end-to-end claim: this calls the compiler with the permission shape
    `gateway/models/ec2net.py::aggregate_permissions` produces. Whether a real
    `tofu apply` writes that span into a live nebula config, and whether it then
    gates real packets, is a container test (`tests/simulate/`), not this one."""
    firewall = sg_rules_to_firewall(
        [{"IpProtocol": "tcp", "FromPort": 8000, "ToPort": 8100,
          "IpRanges": [{"CidrIp": "10.0.0.0/16"}]}],
        [{"IpProtocol": "udp", "FromPort": 9000, "ToPort": 9500,
          "IpRanges": [{"CidrIp": "10.0.0.0/16"}]}],
    )
    assert [(rule.port, rule.proto) for rule in firewall.inbound] == [("8000-8100", "tcp")]
    assert [(rule.port, rule.proto) for rule in firewall.outbound] == [("9000-9500", "udp")]


@pytest.mark.skipif(shutil.which("tofu") is None, reason="tofu not on PATH")
def test_tofu_fmt_accepts_a_group_with_ranges_in_both_directions(tmp_path):
    """This module promises fmt-canonical output, and the widths shift with the
    digits: `8000` is four characters where `443` is three. Measured rather than
    reasoned about -- the last alignment bug here (identity-form rules padding
    to 11) survived review and every existing test."""
    main_tf = tmp_path / "main.tf"
    main_tf.write_text(_main_tf(
        ingressRules="tcp:8000-8100:0.0.0.0/0\ntcp:22:10.0.0.0/16",
        egressRules="udp:9000-9500:web-sg",
    ))
    result = subprocess.run(
        [shutil.which("tofu"), "fmt", "-check", "-diff", str(main_tf)],
        capture_output=True, text=True,
    )
    assert result.returncode == 0, result.stdout + result.stderr


@pytest.mark.skipif(shutil.which("tofu") is None, reason="tofu not on PATH")
async def test_the_real_tofu_validate_accepts_a_ranged_group():
    """The only check of the lot that reads the PROVIDER SCHEMA, and therefore
    the only one that could catch a `from_port`/`to_port` pair the AWS provider
    rejects. Everything above is odin agreeing with odin.

    `tests/agent/test_granted_workload_hcl_validates.py` is the pattern; this
    runs the same `validate_refinement`, which shells out to the same `tofu`
    binary an apply uses."""
    files = {"main.tf": _main_tf(
        ingressRules="tcp:8000-8100:0.0.0.0/0\ntcp:22:10.0.0.0/16",
        egressRules="udp:9000-9500:web-sg",
    )}
    reason, formatted = await validate_refinement(files, files)
    assert reason is None, f"generated Terraform does not validate — {reason}"
    assert formatted is not None
