"""A security group's OUTBOUND rules, authored on the canvas and emitted.

The limit this closes read: "odin re-emits its own wide-open egress
(`0.0.0.0/0`) for every group and has no canvas field for outbound rules, so a
source that restricted egress comes back unrestricted."

The requirement with teeth is the one about what must NOT change: an sg node
with an empty `egressRules` field has to emit BYTE-IDENTICALLY to what it
emitted before the field existed, because that is every canvas ever drawn. The
default is not decoration either -- every `aws_security_group` starts with AWS's
seeded allow-all egress and the TF provider REVOKES it when the config omits an
egress block, so silence would mean "deny all outbound", which is not what those
canvases meant.
"""
from __future__ import annotations

import shutil
import subprocess

import pytest

from odin.agent import hcl
from odin.agent.hcl import generate_tf
from odin.spec.models import FieldValue, ResourceDesired
from odin.spec.translate import canvas_to_stack

# What the emitter produced before `egressRules` existed, transcribed from the
# v0.8.13 source rather than generated by the code under test. A ratchet built
# out of the thing it is ratcheting is no ratchet at all.
_PRE_V0814_DEFAULT_EGRESS = (
    "  egress {\n"
    "    from_port   = 0\n"
    "    to_port     = 0\n"
    '    protocol    = "-1"\n'
    '    cidr_blocks = ["0.0.0.0/0"]\n'
    "  }"
)


def _canvas(**sg_data: str) -> dict:
    return {
        "nodes": [
            {"id": "v", "type": "vpc", "position": {"x": 0, "y": 0}, "data": {"label": "net"}},
            {"id": "w", "type": "sg", "position": {"x": 0, "y": 0},
             "data": {"label": "web-sg", "vpc": "net", "ingressRules": "tcp:443:0.0.0.0/0"}},
            {"id": "s", "type": "sg", "position": {"x": 0, "y": 0},
             "data": {"label": "db-sg", "vpc": "net", **sg_data}},
        ],
        "edges": [],
    }


def _project(**sg_data: str):
    return generate_tf(canvas_to_stack(_canvas(**sg_data)))


def _main_tf(**sg_data: str) -> str:
    return _project(**sg_data).files["main.tf"]


def _db_sg_block(**sg_data: str) -> str:
    """Just the `db-sg` resource. The canvas carries a SECOND group on purpose --
    an identity-form rule needs one to point at -- and that group keeps the
    wide-open default, so a whole-file assertion about the default would be
    reading the wrong block."""
    main_tf = _main_tf(**sg_data)
    rest = main_tf[main_tf.index('resource "aws_security_group" "db_sg"'):]
    return rest[:rest.index("\n}\n")]


def test_an_empty_field_still_emits_the_wide_open_default():
    """The no-change requirement, and the whole reason this test file leads with
    a transcribed literal."""
    assert _PRE_V0814_DEFAULT_EGRESS in _db_sg_block()


def test_a_canvas_with_no_egress_field_at_all_is_unchanged():
    """A node dict that never had the key, which is what a saved canvas from
    before v0.8.14 deserializes to -- distinct from the key present and empty."""
    with_key = _main_tf(egressRules="")
    without_key = _main_tf()
    assert with_key == without_key


def test_authored_rules_replace_the_default_rather_than_joining_it():
    """THE BUG THIS EXISTS FOR. An allow-all block sitting next to a restricted
    one means "allow all" -- the restriction would be decorative, which is the
    same shape as re-emitting it wide open, just harder to notice."""
    block = _db_sg_block(egressRules="tcp:443:10.0.0.0/16")
    assert _PRE_V0814_DEFAULT_EGRESS not in block
    assert '    cidr_blocks = ["10.0.0.0/16"]' in block
    assert block.count("egress {") == 1


def test_every_line_becomes_its_own_block():
    block = _db_sg_block(egressRules="tcp:443:10.0.0.0/16\nudp:53:10.0.0.0/16")
    assert block.count("egress {") == 2
    assert '    protocol    = "udp"' in block
    assert "    from_port   = 53\n    to_port     = 53\n" in block


def test_a_destination_that_names_another_group_becomes_security_groups():
    """The identity form, which is what the Nebula firewall compiles a `group:`
    rule from -- the same resolution `ingressRules` already does, through the
    same function, so the two cannot diverge."""
    assert "    security_groups = [aws_security_group.web_sg.id]" in _db_sg_block(
        egressRules="tcp:5432:web-sg",
    )


def test_the_all_traffic_line_is_byte_identical_to_the_default():
    """So an import may canonicalize a wide-open egress EITHER way -- as an
    empty field or as this one line -- and regenerate the same file. Both halves
    go through `_sg_rule_block`, so this is arithmetic rather than a hope."""
    assert _main_tf(egressRules="-1:0:0.0.0.0/0") == _main_tf()


@pytest.mark.parametrize("rules,expected", [
    ("443 to anywhere", 'egressRules: expected one "protocol:port:destination" rule per line'),
    ("tcp:443:web-tier", "egressRules: destination 'web-tier' is neither a CIDR"),
])
def test_a_bad_egress_line_declines_the_resource_naming_its_own_field(rules: str, expected: str):
    """`egressRules`, not `ingressRules`: a message confidently naming the wrong
    field sends the reader to edit something that was already correct."""
    (reason,) = _project(egressRules=rules).unsupported
    assert expected in reason
    assert "ingressRules" not in reason


@pytest.mark.parametrize("rules,expected", [
    ("443 from anywhere", 'ingressRules: expected one "protocol:port:source" rule per line, '
                          "e.g. tcp:443:0.0.0.0/0"),
    ("tcp:443:web-tier", "ingressRules: source 'web-tier' is neither a CIDR (like 10.0.0.0/16) "
                         "nor the label of another Security Group node on this canvas"),
])
def test_the_ingress_messages_are_unchanged_word_for_word(rules: str, expected: str):
    """One parser now serves both directions, and the ingress half is
    user-facing text that was already correct. Pinned verbatim so generalizing
    the code cannot quietly reword it."""
    (reason,) = _project(ingressRules=rules).unsupported
    assert reason == f"db-sg (sg): {expected}"


@pytest.mark.parametrize("field,word", [("ingressRules", "source"), ("egressRules", "destination")])
def test_an_ipv6_cidr_is_declined_with_the_reason_it_really_fails_for(field: str, word: str):
    """Found by the agent building this grammar's inverse, and the bug was in
    the arity check rather than in IPv6 support: a bare `split(":")` turned
    `tcp:443:2001:db8::/32` into FIVE fields, so the line failed as a format
    error and took the entire security group down with it -- including its other,
    perfectly readable rules. `split(":", 2)` makes the peer one field again, and
    the message then names the real limit instead of a format the user got right.
    """
    (reason,) = _project(**{field: "tcp:443:2001:db8::/32"}).unsupported
    assert f"{field}: {word} '2001:db8::/32' is an IPv6 CIDR" in reason
    assert "IPv4 only" in reason and "nebula" in reason


def test_an_ipv6_line_does_not_take_the_readable_rules_down_as_a_format_error():
    """The old failure's real cost. The message must be about the IPv6 line, not
    about a format the other lines satisfy."""
    (reason,) = _project(ingressRules="tcp:80:0.0.0.0/0\ntcp:443:2001:db8::/32").unsupported
    assert "expected one" not in reason
    assert "IPv6" in reason


def test_a_group_can_restrict_both_directions_at_once():
    block = _db_sg_block(ingressRules="tcp:5432:web-sg", egressRules="tcp:443:10.0.0.0/16")
    assert block.count("ingress {") == 1 and block.count("egress {") == 1
    assert "0.0.0.0/0" not in block


def test_tofu_fmt_accepts_a_group_with_identity_rules_in_both_directions(tmp_path):
    """The formatting half, and it caught a REAL pre-existing defect.

    `security_groups` is 15 characters against `cidr_blocks`' 11, and the old
    emitter pasted a finished line in while padding every other key to 11. On
    OpenTofu 1.12.3 `tofu fmt -check -diff` reported exit 3 and re-padded three
    lines per block -- so this module's "fmt-canonical" claim was false for any
    group with an identity-form ingress rule, and no fmt test covered that shape
    because every one of them used a CIDR. Adding egress would have doubled it.
    """
    tofu = shutil.which("tofu")
    if tofu is None:
        return  # skip cleanly -- no tofu on PATH in this environment
    main_tf = tmp_path / "main.tf"
    main_tf.write_text(_main_tf(ingressRules="tcp:5432:web-sg", egressRules="tcp:5432:web-sg"))
    result = subprocess.run(
        [tofu, "fmt", "-check", "-diff", str(main_tf)], capture_output=True, text=True,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_the_default_rule_is_the_one_the_line_grammar_parses():
    """`_DEFAULT_EGRESS_RULE` has to be spellable as an `egressRules` line, or
    the "identical either way" property above would hold by luck."""
    protocol, port, destination = hcl._DEFAULT_EGRESS_RULE
    res = ResourceDesired(id="db-sg", kind="sg", fields={
        "egressRules": FieldValue(value=f"{protocol}:{port}:{destination}", provenance="user"),
    })
    assert hcl._sg_rules(res, "egressRules") == [(protocol, port, destination)]
